/* This file was automatically generated by CasADi 3.6.7.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) quadrotor_constr_h_0_fun_jac_uxt_zt_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_c1 CASADI_PREFIX(c1)
#define casadi_c2 CASADI_PREFIX(c2)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[10] = {6, 1, 0, 6, 0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s1[7] = {3, 1, 0, 3, 0, 1, 2};
static const casadi_int casadi_s2[3] = {0, 0, 0};
static const casadi_int casadi_s3[5] = {1, 1, 0, 1, 0};
static const casadi_int casadi_s4[7] = {9, 1, 0, 3, 3, 4, 5};
static const casadi_int casadi_s5[3] = {1, 0, 0};

static const casadi_real casadi_c0[9] = {1., 0., 0., 0., 1., 0., 0., 0., 1.0000000000000000e-04};
static const casadi_real casadi_c1[3] = {1., 2., 0.};
static const casadi_real casadi_c2[9] = {1., 0., 0., 0., 1., 0., 0., 0., 1.0000000000000000e-08};

/* quadrotor_constr_h_0_fun_jac_uxt_zt:(i0[6],i1[3],i2[],i3[3])->(o0,o1[9x1,3nz],o2[1x0]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, *ss, *tt;
  const casadi_real *cr, *cs;
  casadi_real *w0=w+3, *w1=w+6, *w2=w+15, *w3=w+18, *w4=w+21, w5, w6;
  /* #0: @0 = zeros(3x1) */
  casadi_clear(w0, 3);
  /* #1: @1 = 
  [[1, 0, 0], 
   [0, 1, 0], 
   [0, 0, 0.0001]] */
  casadi_copy(casadi_c0, 9, w1);
  /* #2: @2 = input[3][0] */
  casadi_copy(arg[3], 3, w2);
  /* #3: @3 = [1, 2, 0] */
  casadi_copy(casadi_c1, 3, w3);
  /* #4: @3 = (@2-@3) */
  for (i=0, rr=w3, cr=w2, cs=w3; i<3; ++i) (*rr++)  = ((*cr++)-(*cs++));
  /* #5: @4 = mac(@1,@3,@0) */
  casadi_copy(w0, 3, w4);
  for (i=0, rr=w4; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w1+j, tt=w3+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #6: @5 = @4[0] */
  for (rr=(&w5), ss=w4+0; ss!=w4+1; ss+=1) *rr++ = *ss;
  /* #7: @5 = sq(@5) */
  w5 = casadi_sq( w5 );
  /* #8: @6 = @4[1] */
  for (rr=(&w6), ss=w4+1; ss!=w4+2; ss+=1) *rr++ = *ss;
  /* #9: @6 = sq(@6) */
  w6 = casadi_sq( w6 );
  /* #10: @5 = (@5+@6) */
  w5 += w6;
  /* #11: @6 = @4[2] */
  for (rr=(&w6), ss=w4+2; ss!=w4+3; ss+=1) *rr++ = *ss;
  /* #12: @6 = sq(@6) */
  w6 = casadi_sq( w6 );
  /* #13: @5 = (@5+@6) */
  w5 += w6;
  /* #14: @5 = sqrt(@5) */
  w5 = sqrt( w5 );
  /* #15: @6 = 0 */
  w6 = 0.;
  /* #16: @1 = 
  [[1, 0, 0], 
   [0, 1, 0], 
   [0, 0, 1e-08]] */
  casadi_copy(casadi_c2, 9, w1);
  /* #17: @0 = mac(@1,@3,@0) */
  for (i=0, rr=w0; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w1+j, tt=w3+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #18: @0 = (@0/@5) */
  for (i=0, rr=w0; i<3; ++i) (*rr++) /= w5;
  /* #19: @3 = @0' */
  casadi_copy(w0, 3, w3);
  /* #20: @4 = input[0][0] */
  casadi_copy(arg[0], 3, w4);
  /* #21: @4 = (@4-@2) */
  for (i=0, rr=w4, cs=w2; i<3; ++i) (*rr++) -= (*cs++);
  /* #22: @6 = mac(@3,@4,@6) */
  for (i=0, rr=(&w6); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w3+j, tt=w4+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #23: @5 = (@5+@6) */
  w5 += w6;
  /* #24: @6 = 1 */
  w6 = 1.;
  /* #25: @5 = (@5-@6) */
  w5 -= w6;
  /* #26: output[0][0] = @5 */
  if (res[0]) res[0][0] = w5;
  /* #27: @3 = zeros(9x1,3nz) */
  casadi_clear(w3, 3);
  /* #28: @5 = @0[0] */
  for (rr=(&w5), ss=w0+0; ss!=w0+1; ss+=1) *rr++ = *ss;
  /* #29: (@3[0] = @5) */
  for (rr=w3+0, ss=(&w5); rr!=w3+1; rr+=1) *rr = *ss++;
  /* #30: @5 = @0[1] */
  for (rr=(&w5), ss=w0+1; ss!=w0+2; ss+=1) *rr++ = *ss;
  /* #31: (@3[1] = @5) */
  for (rr=w3+1, ss=(&w5); rr!=w3+2; rr+=1) *rr = *ss++;
  /* #32: @5 = @0[2] */
  for (rr=(&w5), ss=w0+2; ss!=w0+3; ss+=1) *rr++ = *ss;
  /* #33: (@3[2] = @5) */
  for (rr=w3+2, ss=(&w5); rr!=w3+3; rr+=1) *rr = *ss++;
  /* #34: output[1][0] = @3 */
  casadi_copy(w3, 3, res[1]);
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_constr_h_0_fun_jac_uxt_zt(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int quadrotor_constr_h_0_fun_jac_uxt_zt_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_constr_h_0_fun_jac_uxt_zt_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadrotor_constr_h_0_fun_jac_uxt_zt_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int quadrotor_constr_h_0_fun_jac_uxt_zt_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadrotor_constr_h_0_fun_jac_uxt_zt_release(int mem) {
}

CASADI_SYMBOL_EXPORT void quadrotor_constr_h_0_fun_jac_uxt_zt_incref(void) {
}

CASADI_SYMBOL_EXPORT void quadrotor_constr_h_0_fun_jac_uxt_zt_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int quadrotor_constr_h_0_fun_jac_uxt_zt_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int quadrotor_constr_h_0_fun_jac_uxt_zt_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real quadrotor_constr_h_0_fun_jac_uxt_zt_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadrotor_constr_h_0_fun_jac_uxt_zt_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadrotor_constr_h_0_fun_jac_uxt_zt_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadrotor_constr_h_0_fun_jac_uxt_zt_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadrotor_constr_h_0_fun_jac_uxt_zt_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    case 1: return casadi_s4;
    case 2: return casadi_s5;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int quadrotor_constr_h_0_fun_jac_uxt_zt_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 7;
  if (sz_res) *sz_res = 4;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 26;
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_constr_h_0_fun_jac_uxt_zt_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 7*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 4*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 26*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
