/* This file was automatically generated by CasADi 3.6.7.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) quadrotor_constr_h_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_c1 CASADI_PREFIX(c1)
#define casadi_c2 CASADI_PREFIX(c2)
#define casadi_c3 CASADI_PREFIX(c3)
#define casadi_c4 CASADI_PREFIX(c4)
#define casadi_c5 CASADI_PREFIX(c5)
#define casadi_c6 CASADI_PREFIX(c6)
#define casadi_c7 CASADI_PREFIX(c7)
#define casadi_c8 CASADI_PREFIX(c8)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[16] = {12, 1, 0, 12, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11};
static const casadi_int casadi_s1[8] = {4, 1, 0, 4, 0, 1, 2, 3};
static const casadi_int casadi_s2[3] = {0, 0, 0};
static const casadi_int casadi_s3[7] = {3, 1, 0, 3, 0, 1, 2};
static const casadi_int casadi_s4[11] = {7, 1, 0, 7, 0, 1, 2, 3, 4, 5, 6};

static const casadi_real casadi_c0[9] = {1., 0., 0., 0., 1., 0., 0., 0., 1.0000000000000000e-04};
static const casadi_real casadi_c1[3] = {2., 2., 0.};
static const casadi_real casadi_c2[9] = {1., 0., 0., 0., 1., 0., 0., 0., 1.0000000000000000e-08};
static const casadi_real casadi_c3[3] = {2., 5., 0.};
static const casadi_real casadi_c4[3] = {3., 5., 0.};
static const casadi_real casadi_c5[3] = {-1., 2., 0.};
static const casadi_real casadi_c6[3] = {-5.0000000000000000e-01, 5., 0.};
static const casadi_real casadi_c7[3] = {0., 3., 0.};
static const casadi_real casadi_c8[3] = {0., 0., 1.};

/* quadrotor_constr_h_fun:(i0[12],i1[4],i2[],i3[3])->(o0[7]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, *ss, *tt;
  const casadi_real *cr, *cs;
  casadi_real *w0=w+3, *w1=w+6, *w2=w+15, *w3=w+18, *w4=w+21, w5, w6, *w7=w+26, w8, w9, *w10=w+37, w11, *w12=w+44;
  /* #0: @0 = zeros(3x1) */
  casadi_clear(w0, 3);
  /* #1: @1 = 
  [[1, 0, 0], 
   [0, 1, 0], 
   [0, 0, 0.0001]] */
  casadi_copy(casadi_c0, 9, w1);
  /* #2: @2 = input[3][0] */
  casadi_copy(arg[3], 3, w2);
  /* #3: @3 = [2, 2, 0] */
  casadi_copy(casadi_c1, 3, w3);
  /* #4: @3 = (@2-@3) */
  for (i=0, rr=w3, cr=w2, cs=w3; i<3; ++i) (*rr++)  = ((*cr++)-(*cs++));
  /* #5: @4 = mac(@1,@3,@0) */
  casadi_copy(w0, 3, w4);
  for (i=0, rr=w4; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w1+j, tt=w3+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #6: @5 = @4[0] */
  for (rr=(&w5), ss=w4+0; ss!=w4+1; ss+=1) *rr++ = *ss;
  /* #7: @5 = sq(@5) */
  w5 = casadi_sq( w5 );
  /* #8: @6 = @4[1] */
  for (rr=(&w6), ss=w4+1; ss!=w4+2; ss+=1) *rr++ = *ss;
  /* #9: @6 = sq(@6) */
  w6 = casadi_sq( w6 );
  /* #10: @5 = (@5+@6) */
  w5 += w6;
  /* #11: @6 = @4[2] */
  for (rr=(&w6), ss=w4+2; ss!=w4+3; ss+=1) *rr++ = *ss;
  /* #12: @6 = sq(@6) */
  w6 = casadi_sq( w6 );
  /* #13: @5 = (@5+@6) */
  w5 += w6;
  /* #14: @5 = sqrt(@5) */
  w5 = sqrt( w5 );
  /* #15: @6 = 0 */
  w6 = 0.;
  /* #16: @7 = 
  [[1, 0, 0], 
   [0, 1, 0], 
   [0, 0, 1e-08]] */
  casadi_copy(casadi_c2, 9, w7);
  /* #17: @4 = mac(@7,@3,@0) */
  casadi_copy(w0, 3, w4);
  for (i=0, rr=w4; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w7+j, tt=w3+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #18: @8 = 0.001 */
  w8 = 1.0000000000000000e-03;
  /* #19: @9 = (@8+@5) */
  w9  = (w8+w5);
  /* #20: @4 = (@4/@9) */
  for (i=0, rr=w4; i<3; ++i) (*rr++) /= w9;
  /* #21: @4 = @4' */
  /* #22: @3 = input[0][0] */
  casadi_copy(arg[0], 3, w3);
  /* #23: @3 = (@3-@2) */
  for (i=0, rr=w3, cs=w2; i<3; ++i) (*rr++) -= (*cs++);
  /* #24: @9 = mac(@4,@3,@6) */
  casadi_copy((&w6), 1, (&w9));
  for (i=0, rr=(&w9); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w4+j, tt=w3+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #25: @5 = (@5+@9) */
  w5 += w9;
  /* #26: @9 = 1 */
  w9 = 1.;
  /* #27: @5 = (@5-@9) */
  w5 -= w9;
  /* #28: @10 = input[0][2] */
  casadi_copy(arg[0] ? arg[0]+6 : 0, 6, w10);
  /* #29: @11 = @10[0] */
  for (rr=(&w11), ss=w10+0; ss!=w10+1; ss+=1) *rr++ = *ss;
  /* #30: @5 = (@5+@11) */
  w5 += w11;
  /* #31: output[0][0] = @5 */
  if (res[0]) res[0][0] = w5;
  /* #32: @4 = [2, 5, 0] */
  casadi_copy(casadi_c3, 3, w4);
  /* #33: @4 = (@2-@4) */
  for (i=0, rr=w4, cr=w2, cs=w4; i<3; ++i) (*rr++)  = ((*cr++)-(*cs++));
  /* #34: @12 = mac(@1,@4,@0) */
  casadi_copy(w0, 3, w12);
  for (i=0, rr=w12; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w1+j, tt=w4+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #35: @5 = @12[0] */
  for (rr=(&w5), ss=w12+0; ss!=w12+1; ss+=1) *rr++ = *ss;
  /* #36: @5 = sq(@5) */
  w5 = casadi_sq( w5 );
  /* #37: @11 = @12[1] */
  for (rr=(&w11), ss=w12+1; ss!=w12+2; ss+=1) *rr++ = *ss;
  /* #38: @11 = sq(@11) */
  w11 = casadi_sq( w11 );
  /* #39: @5 = (@5+@11) */
  w5 += w11;
  /* #40: @11 = @12[2] */
  for (rr=(&w11), ss=w12+2; ss!=w12+3; ss+=1) *rr++ = *ss;
  /* #41: @11 = sq(@11) */
  w11 = casadi_sq( w11 );
  /* #42: @5 = (@5+@11) */
  w5 += w11;
  /* #43: @5 = sqrt(@5) */
  w5 = sqrt( w5 );
  /* #44: @12 = mac(@7,@4,@0) */
  casadi_copy(w0, 3, w12);
  for (i=0, rr=w12; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w7+j, tt=w4+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #45: @11 = (@8+@5) */
  w11  = (w8+w5);
  /* #46: @12 = (@12/@11) */
  for (i=0, rr=w12; i<3; ++i) (*rr++) /= w11;
  /* #47: @12 = @12' */
  /* #48: @11 = mac(@12,@3,@6) */
  casadi_copy((&w6), 1, (&w11));
  for (i=0, rr=(&w11); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w12+j, tt=w3+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #49: @5 = (@5+@11) */
  w5 += w11;
  /* #50: @5 = (@5-@9) */
  w5 -= w9;
  /* #51: @11 = @10[1] */
  for (rr=(&w11), ss=w10+1; ss!=w10+2; ss+=1) *rr++ = *ss;
  /* #52: @5 = (@5+@11) */
  w5 += w11;
  /* #53: output[0][1] = @5 */
  if (res[0]) res[0][1] = w5;
  /* #54: @12 = [3, 5, 0] */
  casadi_copy(casadi_c4, 3, w12);
  /* #55: @12 = (@2-@12) */
  for (i=0, rr=w12, cr=w2, cs=w12; i<3; ++i) (*rr++)  = ((*cr++)-(*cs++));
  /* #56: @4 = mac(@1,@12,@0) */
  casadi_copy(w0, 3, w4);
  for (i=0, rr=w4; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w1+j, tt=w12+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #57: @5 = @4[0] */
  for (rr=(&w5), ss=w4+0; ss!=w4+1; ss+=1) *rr++ = *ss;
  /* #58: @5 = sq(@5) */
  w5 = casadi_sq( w5 );
  /* #59: @11 = @4[1] */
  for (rr=(&w11), ss=w4+1; ss!=w4+2; ss+=1) *rr++ = *ss;
  /* #60: @11 = sq(@11) */
  w11 = casadi_sq( w11 );
  /* #61: @5 = (@5+@11) */
  w5 += w11;
  /* #62: @11 = @4[2] */
  for (rr=(&w11), ss=w4+2; ss!=w4+3; ss+=1) *rr++ = *ss;
  /* #63: @11 = sq(@11) */
  w11 = casadi_sq( w11 );
  /* #64: @5 = (@5+@11) */
  w5 += w11;
  /* #65: @5 = sqrt(@5) */
  w5 = sqrt( w5 );
  /* #66: @4 = mac(@7,@12,@0) */
  casadi_copy(w0, 3, w4);
  for (i=0, rr=w4; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w7+j, tt=w12+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #67: @11 = (@8+@5) */
  w11  = (w8+w5);
  /* #68: @4 = (@4/@11) */
  for (i=0, rr=w4; i<3; ++i) (*rr++) /= w11;
  /* #69: @4 = @4' */
  /* #70: @11 = mac(@4,@3,@6) */
  casadi_copy((&w6), 1, (&w11));
  for (i=0, rr=(&w11); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w4+j, tt=w3+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #71: @5 = (@5+@11) */
  w5 += w11;
  /* #72: @5 = (@5-@9) */
  w5 -= w9;
  /* #73: @11 = @10[2] */
  for (rr=(&w11), ss=w10+2; ss!=w10+3; ss+=1) *rr++ = *ss;
  /* #74: @5 = (@5+@11) */
  w5 += w11;
  /* #75: output[0][2] = @5 */
  if (res[0]) res[0][2] = w5;
  /* #76: @4 = [-1, 2, 0] */
  casadi_copy(casadi_c5, 3, w4);
  /* #77: @4 = (@2-@4) */
  for (i=0, rr=w4, cr=w2, cs=w4; i<3; ++i) (*rr++)  = ((*cr++)-(*cs++));
  /* #78: @12 = mac(@1,@4,@0) */
  casadi_copy(w0, 3, w12);
  for (i=0, rr=w12; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w1+j, tt=w4+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #79: @5 = @12[0] */
  for (rr=(&w5), ss=w12+0; ss!=w12+1; ss+=1) *rr++ = *ss;
  /* #80: @5 = sq(@5) */
  w5 = casadi_sq( w5 );
  /* #81: @11 = @12[1] */
  for (rr=(&w11), ss=w12+1; ss!=w12+2; ss+=1) *rr++ = *ss;
  /* #82: @11 = sq(@11) */
  w11 = casadi_sq( w11 );
  /* #83: @5 = (@5+@11) */
  w5 += w11;
  /* #84: @11 = @12[2] */
  for (rr=(&w11), ss=w12+2; ss!=w12+3; ss+=1) *rr++ = *ss;
  /* #85: @11 = sq(@11) */
  w11 = casadi_sq( w11 );
  /* #86: @5 = (@5+@11) */
  w5 += w11;
  /* #87: @5 = sqrt(@5) */
  w5 = sqrt( w5 );
  /* #88: @12 = mac(@7,@4,@0) */
  casadi_copy(w0, 3, w12);
  for (i=0, rr=w12; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w7+j, tt=w4+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #89: @11 = (@8+@5) */
  w11  = (w8+w5);
  /* #90: @12 = (@12/@11) */
  for (i=0, rr=w12; i<3; ++i) (*rr++) /= w11;
  /* #91: @12 = @12' */
  /* #92: @11 = mac(@12,@3,@6) */
  casadi_copy((&w6), 1, (&w11));
  for (i=0, rr=(&w11); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w12+j, tt=w3+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #93: @5 = (@5+@11) */
  w5 += w11;
  /* #94: @5 = (@5-@9) */
  w5 -= w9;
  /* #95: @11 = @10[3] */
  for (rr=(&w11), ss=w10+3; ss!=w10+4; ss+=1) *rr++ = *ss;
  /* #96: @5 = (@5+@11) */
  w5 += w11;
  /* #97: output[0][3] = @5 */
  if (res[0]) res[0][3] = w5;
  /* #98: @12 = [-0.5, 5, 0] */
  casadi_copy(casadi_c6, 3, w12);
  /* #99: @12 = (@2-@12) */
  for (i=0, rr=w12, cr=w2, cs=w12; i<3; ++i) (*rr++)  = ((*cr++)-(*cs++));
  /* #100: @4 = mac(@1,@12,@0) */
  casadi_copy(w0, 3, w4);
  for (i=0, rr=w4; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w1+j, tt=w12+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #101: @5 = @4[0] */
  for (rr=(&w5), ss=w4+0; ss!=w4+1; ss+=1) *rr++ = *ss;
  /* #102: @5 = sq(@5) */
  w5 = casadi_sq( w5 );
  /* #103: @11 = @4[1] */
  for (rr=(&w11), ss=w4+1; ss!=w4+2; ss+=1) *rr++ = *ss;
  /* #104: @11 = sq(@11) */
  w11 = casadi_sq( w11 );
  /* #105: @5 = (@5+@11) */
  w5 += w11;
  /* #106: @11 = @4[2] */
  for (rr=(&w11), ss=w4+2; ss!=w4+3; ss+=1) *rr++ = *ss;
  /* #107: @11 = sq(@11) */
  w11 = casadi_sq( w11 );
  /* #108: @5 = (@5+@11) */
  w5 += w11;
  /* #109: @5 = sqrt(@5) */
  w5 = sqrt( w5 );
  /* #110: @4 = mac(@7,@12,@0) */
  casadi_copy(w0, 3, w4);
  for (i=0, rr=w4; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w7+j, tt=w12+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #111: @11 = (@8+@5) */
  w11  = (w8+w5);
  /* #112: @4 = (@4/@11) */
  for (i=0, rr=w4; i<3; ++i) (*rr++) /= w11;
  /* #113: @4 = @4' */
  /* #114: @11 = mac(@4,@3,@6) */
  casadi_copy((&w6), 1, (&w11));
  for (i=0, rr=(&w11); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w4+j, tt=w3+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #115: @5 = (@5+@11) */
  w5 += w11;
  /* #116: @5 = (@5-@9) */
  w5 -= w9;
  /* #117: @11 = @10[4] */
  for (rr=(&w11), ss=w10+4; ss!=w10+5; ss+=1) *rr++ = *ss;
  /* #118: @5 = (@5+@11) */
  w5 += w11;
  /* #119: output[0][4] = @5 */
  if (res[0]) res[0][4] = w5;
  /* #120: @4 = [0, 3, 0] */
  casadi_copy(casadi_c7, 3, w4);
  /* #121: @2 = (@2-@4) */
  for (i=0, rr=w2, cs=w4; i<3; ++i) (*rr++) -= (*cs++);
  /* #122: @4 = mac(@1,@2,@0) */
  casadi_copy(w0, 3, w4);
  for (i=0, rr=w4; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w1+j, tt=w2+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #123: @5 = @4[0] */
  for (rr=(&w5), ss=w4+0; ss!=w4+1; ss+=1) *rr++ = *ss;
  /* #124: @5 = sq(@5) */
  w5 = casadi_sq( w5 );
  /* #125: @11 = @4[1] */
  for (rr=(&w11), ss=w4+1; ss!=w4+2; ss+=1) *rr++ = *ss;
  /* #126: @11 = sq(@11) */
  w11 = casadi_sq( w11 );
  /* #127: @5 = (@5+@11) */
  w5 += w11;
  /* #128: @11 = @4[2] */
  for (rr=(&w11), ss=w4+2; ss!=w4+3; ss+=1) *rr++ = *ss;
  /* #129: @11 = sq(@11) */
  w11 = casadi_sq( w11 );
  /* #130: @5 = (@5+@11) */
  w5 += w11;
  /* #131: @5 = sqrt(@5) */
  w5 = sqrt( w5 );
  /* #132: @0 = mac(@7,@2,@0) */
  for (i=0, rr=w0; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w7+j, tt=w2+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #133: @8 = (@8+@5) */
  w8 += w5;
  /* #134: @0 = (@0/@8) */
  for (i=0, rr=w0; i<3; ++i) (*rr++) /= w8;
  /* #135: @0 = @0' */
  /* #136: @8 = mac(@0,@3,@6) */
  casadi_copy((&w6), 1, (&w8));
  for (i=0, rr=(&w8); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w0+j, tt=w3+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #137: @5 = (@5+@8) */
  w5 += w8;
  /* #138: @5 = (@5-@9) */
  w5 -= w9;
  /* #139: @9 = @10[5] */
  for (rr=(&w9), ss=w10+5; ss!=w10+6; ss+=1) *rr++ = *ss;
  /* #140: @5 = (@5+@9) */
  w5 += w9;
  /* #141: output[0][5] = @5 */
  if (res[0]) res[0][5] = w5;
  /* #142: @0 = [0, 0, 1] */
  casadi_copy(casadi_c8, 3, w0);
  /* #143: @0 = @0' */
  /* #144: @3 = input[1][0] */
  casadi_copy(arg[1], 3, w3);
  /* #145: @6 = mac(@0,@3,@6) */
  for (i=0, rr=(&w6); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w0+j, tt=w3+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #146: @5 = -0.173648 */
  w5 = -1.7364817766693030e-01;
  /* #147: @9 = input[1][1] */
  w9 = arg[1] ? arg[1][3] : 0;
  /* #148: @5 = (@5*@9) */
  w5 *= w9;
  /* #149: @6 = (@6-@5) */
  w6 -= w5;
  /* #150: output[0][6] = @6 */
  if (res[0]) res[0][6] = w6;
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_constr_h_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int quadrotor_constr_h_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_constr_h_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadrotor_constr_h_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int quadrotor_constr_h_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadrotor_constr_h_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void quadrotor_constr_h_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void quadrotor_constr_h_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int quadrotor_constr_h_fun_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int quadrotor_constr_h_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real quadrotor_constr_h_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadrotor_constr_h_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadrotor_constr_h_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadrotor_constr_h_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadrotor_constr_h_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int quadrotor_constr_h_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 7;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 47;
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_constr_h_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 7*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 2*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 47*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
