/* This file was automatically generated by CasADi 3.6.7.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) quadrotor_constr_h_fun_jac_uxt_zt_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_c1 CASADI_PREFIX(c1)
#define casadi_c2 CASADI_PREFIX(c2)
#define casadi_c3 CASADI_PREFIX(c3)
#define casadi_c4 CASADI_PREFIX(c4)
#define casadi_c5 CASADI_PREFIX(c5)
#define casadi_c6 CASADI_PREFIX(c6)
#define casadi_c7 CASADI_PREFIX(c7)
#define casadi_c8 CASADI_PREFIX(c8)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_mtimes CASADI_PREFIX(mtimes)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s10 CASADI_PREFIX(s10)
#define casadi_s11 CASADI_PREFIX(s11)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_s9 CASADI_PREFIX(s9)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

void casadi_mtimes(const casadi_real* x, const casadi_int* sp_x, const casadi_real* y, const casadi_int* sp_y, casadi_real* z, const casadi_int* sp_z, casadi_real* w, casadi_int tr) {
  casadi_int ncol_x, ncol_y, ncol_z, cc;
  const casadi_int *colind_x, *row_x, *colind_y, *row_y, *colind_z, *row_z;
  ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y + 2 + ncol_y+1;
  ncol_z = sp_z[1];
  colind_z = sp_z+2; row_z = sp_z + 2 + ncol_z+1;
  if (tr) {
    for (cc=0; cc<ncol_z; ++cc) {
      casadi_int kk;
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        w[row_y[kk]] = y[kk];
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_z[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          z[kk] += x[kk1] * w[row_x[kk1]];
        }
      }
    }
  } else {
    for (cc=0; cc<ncol_y; ++cc) {
      casadi_int kk;
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        w[row_z[kk]] = z[kk];
      }
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_y[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          w[row_x[kk1]] += x[kk1]*y[kk];
        }
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        z[kk] = w[row_z[kk]];
      }
    }
  }
}

static const casadi_int casadi_s0[5] = {1, 1, 0, 1, 0};
static const casadi_int casadi_s1[5] = {3, 1, 0, 1, 0};
static const casadi_int casadi_s2[9] = {1, 3, 0, 1, 2, 3, 0, 0, 0};
static const casadi_int casadi_s3[5] = {3, 1, 0, 1, 1};
static const casadi_int casadi_s4[5] = {3, 1, 0, 1, 2};
static const casadi_int casadi_s5[16] = {12, 1, 0, 12, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11};
static const casadi_int casadi_s6[8] = {4, 1, 0, 4, 0, 1, 2, 3};
static const casadi_int casadi_s7[3] = {0, 0, 0};
static const casadi_int casadi_s8[7] = {3, 1, 0, 3, 0, 1, 2};
static const casadi_int casadi_s9[11] = {7, 1, 0, 7, 0, 1, 2, 3, 4, 5, 6};
static const casadi_int casadi_s10[38] = {16, 7, 0, 4, 8, 12, 16, 20, 24, 28, 4, 5, 6, 10, 4, 5, 6, 11, 4, 5, 6, 12, 4, 5, 6, 13, 4, 5, 6, 14, 4, 5, 6, 15, 0, 1, 2, 3};
static const casadi_int casadi_s11[3] = {7, 0, 0};

static const casadi_real casadi_c0[9] = {1., 0., 0., 0., 1., 0., 0., 0., 1.0000000000000000e-04};
static const casadi_real casadi_c1[3] = {2., 2., 0.};
static const casadi_real casadi_c2[9] = {1., 0., 0., 0., 1., 0., 0., 0., 1.0000000000000000e-08};
static const casadi_real casadi_c3[3] = {2., 5., 0.};
static const casadi_real casadi_c4[3] = {3., 5., 0.};
static const casadi_real casadi_c5[3] = {-1., 2., 0.};
static const casadi_real casadi_c6[3] = {-5.0000000000000000e-01, 5., 0.};
static const casadi_real casadi_c7[3] = {0., 3., 0.};
static const casadi_real casadi_c8[3] = {0., 0., 1.};

/* quadrotor_constr_h_fun_jac_uxt_zt:(i0[12],i1[4],i2[],i3[3])->(o0[7],o1[16x7,28nz],o2[7x0]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, *ss, *tt;
  const casadi_real *cr, *cs;
  casadi_real *w0=w+3, *w1=w+6, *w2=w+15, *w3=w+18, *w4=w+21, w5, w6, *w7=w+26, w8, w9, *w10=w+37, w11, *w12=w+44, *w13=w+47, *w14=w+50, *w15=w+53, *w16=w+56, *w17=w+59, *w18=w+87, w19, w20, w21, w22, w23, *w24=w+97, *w25=w+104;
  /* #0: @0 = zeros(3x1) */
  casadi_clear(w0, 3);
  /* #1: @1 = 
  [[1, 0, 0], 
   [0, 1, 0], 
   [0, 0, 0.0001]] */
  casadi_copy(casadi_c0, 9, w1);
  /* #2: @2 = input[3][0] */
  casadi_copy(arg[3], 3, w2);
  /* #3: @3 = [2, 2, 0] */
  casadi_copy(casadi_c1, 3, w3);
  /* #4: @3 = (@2-@3) */
  for (i=0, rr=w3, cr=w2, cs=w3; i<3; ++i) (*rr++)  = ((*cr++)-(*cs++));
  /* #5: @4 = mac(@1,@3,@0) */
  casadi_copy(w0, 3, w4);
  for (i=0, rr=w4; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w1+j, tt=w3+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #6: @5 = @4[0] */
  for (rr=(&w5), ss=w4+0; ss!=w4+1; ss+=1) *rr++ = *ss;
  /* #7: @5 = sq(@5) */
  w5 = casadi_sq( w5 );
  /* #8: @6 = @4[1] */
  for (rr=(&w6), ss=w4+1; ss!=w4+2; ss+=1) *rr++ = *ss;
  /* #9: @6 = sq(@6) */
  w6 = casadi_sq( w6 );
  /* #10: @5 = (@5+@6) */
  w5 += w6;
  /* #11: @6 = @4[2] */
  for (rr=(&w6), ss=w4+2; ss!=w4+3; ss+=1) *rr++ = *ss;
  /* #12: @6 = sq(@6) */
  w6 = casadi_sq( w6 );
  /* #13: @5 = (@5+@6) */
  w5 += w6;
  /* #14: @5 = sqrt(@5) */
  w5 = sqrt( w5 );
  /* #15: @6 = 0 */
  w6 = 0.;
  /* #16: @7 = 
  [[1, 0, 0], 
   [0, 1, 0], 
   [0, 0, 1e-08]] */
  casadi_copy(casadi_c2, 9, w7);
  /* #17: @4 = mac(@7,@3,@0) */
  casadi_copy(w0, 3, w4);
  for (i=0, rr=w4; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w7+j, tt=w3+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #18: @8 = 0.001 */
  w8 = 1.0000000000000000e-03;
  /* #19: @9 = (@8+@5) */
  w9  = (w8+w5);
  /* #20: @4 = (@4/@9) */
  for (i=0, rr=w4; i<3; ++i) (*rr++) /= w9;
  /* #21: @4 = @4' */
  /* #22: @3 = input[0][0] */
  casadi_copy(arg[0], 3, w3);
  /* #23: @3 = (@3-@2) */
  for (i=0, rr=w3, cs=w2; i<3; ++i) (*rr++) -= (*cs++);
  /* #24: @9 = mac(@4,@3,@6) */
  casadi_copy((&w6), 1, (&w9));
  for (i=0, rr=(&w9); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w4+j, tt=w3+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #25: @5 = (@5+@9) */
  w5 += w9;
  /* #26: @9 = 1 */
  w9 = 1.;
  /* #27: @5 = (@5-@9) */
  w5 -= w9;
  /* #28: @10 = input[0][2] */
  casadi_copy(arg[0] ? arg[0]+6 : 0, 6, w10);
  /* #29: @11 = @10[0] */
  for (rr=(&w11), ss=w10+0; ss!=w10+1; ss+=1) *rr++ = *ss;
  /* #30: @5 = (@5+@11) */
  w5 += w11;
  /* #31: output[0][0] = @5 */
  if (res[0]) res[0][0] = w5;
  /* #32: @12 = [2, 5, 0] */
  casadi_copy(casadi_c3, 3, w12);
  /* #33: @12 = (@2-@12) */
  for (i=0, rr=w12, cr=w2, cs=w12; i<3; ++i) (*rr++)  = ((*cr++)-(*cs++));
  /* #34: @13 = mac(@1,@12,@0) */
  casadi_copy(w0, 3, w13);
  for (i=0, rr=w13; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w1+j, tt=w12+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #35: @5 = @13[0] */
  for (rr=(&w5), ss=w13+0; ss!=w13+1; ss+=1) *rr++ = *ss;
  /* #36: @5 = sq(@5) */
  w5 = casadi_sq( w5 );
  /* #37: @11 = @13[1] */
  for (rr=(&w11), ss=w13+1; ss!=w13+2; ss+=1) *rr++ = *ss;
  /* #38: @11 = sq(@11) */
  w11 = casadi_sq( w11 );
  /* #39: @5 = (@5+@11) */
  w5 += w11;
  /* #40: @11 = @13[2] */
  for (rr=(&w11), ss=w13+2; ss!=w13+3; ss+=1) *rr++ = *ss;
  /* #41: @11 = sq(@11) */
  w11 = casadi_sq( w11 );
  /* #42: @5 = (@5+@11) */
  w5 += w11;
  /* #43: @5 = sqrt(@5) */
  w5 = sqrt( w5 );
  /* #44: @13 = mac(@7,@12,@0) */
  casadi_copy(w0, 3, w13);
  for (i=0, rr=w13; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w7+j, tt=w12+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #45: @11 = (@8+@5) */
  w11  = (w8+w5);
  /* #46: @13 = (@13/@11) */
  for (i=0, rr=w13; i<3; ++i) (*rr++) /= w11;
  /* #47: @13 = @13' */
  /* #48: @11 = mac(@13,@3,@6) */
  casadi_copy((&w6), 1, (&w11));
  for (i=0, rr=(&w11); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w13+j, tt=w3+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #49: @5 = (@5+@11) */
  w5 += w11;
  /* #50: @5 = (@5-@9) */
  w5 -= w9;
  /* #51: @11 = @10[1] */
  for (rr=(&w11), ss=w10+1; ss!=w10+2; ss+=1) *rr++ = *ss;
  /* #52: @5 = (@5+@11) */
  w5 += w11;
  /* #53: output[0][1] = @5 */
  if (res[0]) res[0][1] = w5;
  /* #54: @12 = [3, 5, 0] */
  casadi_copy(casadi_c4, 3, w12);
  /* #55: @12 = (@2-@12) */
  for (i=0, rr=w12, cr=w2, cs=w12; i<3; ++i) (*rr++)  = ((*cr++)-(*cs++));
  /* #56: @14 = mac(@1,@12,@0) */
  casadi_copy(w0, 3, w14);
  for (i=0, rr=w14; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w1+j, tt=w12+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #57: @5 = @14[0] */
  for (rr=(&w5), ss=w14+0; ss!=w14+1; ss+=1) *rr++ = *ss;
  /* #58: @5 = sq(@5) */
  w5 = casadi_sq( w5 );
  /* #59: @11 = @14[1] */
  for (rr=(&w11), ss=w14+1; ss!=w14+2; ss+=1) *rr++ = *ss;
  /* #60: @11 = sq(@11) */
  w11 = casadi_sq( w11 );
  /* #61: @5 = (@5+@11) */
  w5 += w11;
  /* #62: @11 = @14[2] */
  for (rr=(&w11), ss=w14+2; ss!=w14+3; ss+=1) *rr++ = *ss;
  /* #63: @11 = sq(@11) */
  w11 = casadi_sq( w11 );
  /* #64: @5 = (@5+@11) */
  w5 += w11;
  /* #65: @5 = sqrt(@5) */
  w5 = sqrt( w5 );
  /* #66: @14 = mac(@7,@12,@0) */
  casadi_copy(w0, 3, w14);
  for (i=0, rr=w14; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w7+j, tt=w12+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #67: @11 = (@8+@5) */
  w11  = (w8+w5);
  /* #68: @14 = (@14/@11) */
  for (i=0, rr=w14; i<3; ++i) (*rr++) /= w11;
  /* #69: @14 = @14' */
  /* #70: @11 = mac(@14,@3,@6) */
  casadi_copy((&w6), 1, (&w11));
  for (i=0, rr=(&w11); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w14+j, tt=w3+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #71: @5 = (@5+@11) */
  w5 += w11;
  /* #72: @5 = (@5-@9) */
  w5 -= w9;
  /* #73: @11 = @10[2] */
  for (rr=(&w11), ss=w10+2; ss!=w10+3; ss+=1) *rr++ = *ss;
  /* #74: @5 = (@5+@11) */
  w5 += w11;
  /* #75: output[0][2] = @5 */
  if (res[0]) res[0][2] = w5;
  /* #76: @12 = [-1, 2, 0] */
  casadi_copy(casadi_c5, 3, w12);
  /* #77: @12 = (@2-@12) */
  for (i=0, rr=w12, cr=w2, cs=w12; i<3; ++i) (*rr++)  = ((*cr++)-(*cs++));
  /* #78: @15 = mac(@1,@12,@0) */
  casadi_copy(w0, 3, w15);
  for (i=0, rr=w15; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w1+j, tt=w12+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #79: @5 = @15[0] */
  for (rr=(&w5), ss=w15+0; ss!=w15+1; ss+=1) *rr++ = *ss;
  /* #80: @5 = sq(@5) */
  w5 = casadi_sq( w5 );
  /* #81: @11 = @15[1] */
  for (rr=(&w11), ss=w15+1; ss!=w15+2; ss+=1) *rr++ = *ss;
  /* #82: @11 = sq(@11) */
  w11 = casadi_sq( w11 );
  /* #83: @5 = (@5+@11) */
  w5 += w11;
  /* #84: @11 = @15[2] */
  for (rr=(&w11), ss=w15+2; ss!=w15+3; ss+=1) *rr++ = *ss;
  /* #85: @11 = sq(@11) */
  w11 = casadi_sq( w11 );
  /* #86: @5 = (@5+@11) */
  w5 += w11;
  /* #87: @5 = sqrt(@5) */
  w5 = sqrt( w5 );
  /* #88: @15 = mac(@7,@12,@0) */
  casadi_copy(w0, 3, w15);
  for (i=0, rr=w15; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w7+j, tt=w12+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #89: @11 = (@8+@5) */
  w11  = (w8+w5);
  /* #90: @15 = (@15/@11) */
  for (i=0, rr=w15; i<3; ++i) (*rr++) /= w11;
  /* #91: @15 = @15' */
  /* #92: @11 = mac(@15,@3,@6) */
  casadi_copy((&w6), 1, (&w11));
  for (i=0, rr=(&w11); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w15+j, tt=w3+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #93: @5 = (@5+@11) */
  w5 += w11;
  /* #94: @5 = (@5-@9) */
  w5 -= w9;
  /* #95: @11 = @10[3] */
  for (rr=(&w11), ss=w10+3; ss!=w10+4; ss+=1) *rr++ = *ss;
  /* #96: @5 = (@5+@11) */
  w5 += w11;
  /* #97: output[0][3] = @5 */
  if (res[0]) res[0][3] = w5;
  /* #98: @12 = [-0.5, 5, 0] */
  casadi_copy(casadi_c6, 3, w12);
  /* #99: @12 = (@2-@12) */
  for (i=0, rr=w12, cr=w2, cs=w12; i<3; ++i) (*rr++)  = ((*cr++)-(*cs++));
  /* #100: @16 = mac(@1,@12,@0) */
  casadi_copy(w0, 3, w16);
  for (i=0, rr=w16; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w1+j, tt=w12+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #101: @5 = @16[0] */
  for (rr=(&w5), ss=w16+0; ss!=w16+1; ss+=1) *rr++ = *ss;
  /* #102: @5 = sq(@5) */
  w5 = casadi_sq( w5 );
  /* #103: @11 = @16[1] */
  for (rr=(&w11), ss=w16+1; ss!=w16+2; ss+=1) *rr++ = *ss;
  /* #104: @11 = sq(@11) */
  w11 = casadi_sq( w11 );
  /* #105: @5 = (@5+@11) */
  w5 += w11;
  /* #106: @11 = @16[2] */
  for (rr=(&w11), ss=w16+2; ss!=w16+3; ss+=1) *rr++ = *ss;
  /* #107: @11 = sq(@11) */
  w11 = casadi_sq( w11 );
  /* #108: @5 = (@5+@11) */
  w5 += w11;
  /* #109: @5 = sqrt(@5) */
  w5 = sqrt( w5 );
  /* #110: @16 = mac(@7,@12,@0) */
  casadi_copy(w0, 3, w16);
  for (i=0, rr=w16; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w7+j, tt=w12+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #111: @11 = (@8+@5) */
  w11  = (w8+w5);
  /* #112: @16 = (@16/@11) */
  for (i=0, rr=w16; i<3; ++i) (*rr++) /= w11;
  /* #113: @16 = @16' */
  /* #114: @11 = mac(@16,@3,@6) */
  casadi_copy((&w6), 1, (&w11));
  for (i=0, rr=(&w11); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w16+j, tt=w3+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #115: @5 = (@5+@11) */
  w5 += w11;
  /* #116: @5 = (@5-@9) */
  w5 -= w9;
  /* #117: @11 = @10[4] */
  for (rr=(&w11), ss=w10+4; ss!=w10+5; ss+=1) *rr++ = *ss;
  /* #118: @5 = (@5+@11) */
  w5 += w11;
  /* #119: output[0][4] = @5 */
  if (res[0]) res[0][4] = w5;
  /* #120: @12 = [0, 3, 0] */
  casadi_copy(casadi_c7, 3, w12);
  /* #121: @2 = (@2-@12) */
  for (i=0, rr=w2, cs=w12; i<3; ++i) (*rr++) -= (*cs++);
  /* #122: @12 = mac(@1,@2,@0) */
  casadi_copy(w0, 3, w12);
  for (i=0, rr=w12; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w1+j, tt=w2+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #123: @5 = @12[0] */
  for (rr=(&w5), ss=w12+0; ss!=w12+1; ss+=1) *rr++ = *ss;
  /* #124: @5 = sq(@5) */
  w5 = casadi_sq( w5 );
  /* #125: @11 = @12[1] */
  for (rr=(&w11), ss=w12+1; ss!=w12+2; ss+=1) *rr++ = *ss;
  /* #126: @11 = sq(@11) */
  w11 = casadi_sq( w11 );
  /* #127: @5 = (@5+@11) */
  w5 += w11;
  /* #128: @11 = @12[2] */
  for (rr=(&w11), ss=w12+2; ss!=w12+3; ss+=1) *rr++ = *ss;
  /* #129: @11 = sq(@11) */
  w11 = casadi_sq( w11 );
  /* #130: @5 = (@5+@11) */
  w5 += w11;
  /* #131: @5 = sqrt(@5) */
  w5 = sqrt( w5 );
  /* #132: @0 = mac(@7,@2,@0) */
  for (i=0, rr=w0; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w7+j, tt=w2+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #133: @8 = (@8+@5) */
  w8 += w5;
  /* #134: @0 = (@0/@8) */
  for (i=0, rr=w0; i<3; ++i) (*rr++) /= w8;
  /* #135: @0 = @0' */
  /* #136: @8 = mac(@0,@3,@6) */
  casadi_copy((&w6), 1, (&w8));
  for (i=0, rr=(&w8); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w0+j, tt=w3+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #137: @5 = (@5+@8) */
  w5 += w8;
  /* #138: @5 = (@5-@9) */
  w5 -= w9;
  /* #139: @9 = @10[5] */
  for (rr=(&w9), ss=w10+5; ss!=w10+6; ss+=1) *rr++ = *ss;
  /* #140: @5 = (@5+@9) */
  w5 += w9;
  /* #141: output[0][5] = @5 */
  if (res[0]) res[0][5] = w5;
  /* #142: @3 = [0, 0, 1] */
  casadi_copy(casadi_c8, 3, w3);
  /* #143: @3 = @3' */
  /* #144: @2 = input[1][0] */
  casadi_copy(arg[1], 3, w2);
  /* #145: @5 = mac(@3,@2,@6) */
  casadi_copy((&w6), 1, (&w5));
  for (i=0, rr=(&w5); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w3+j, tt=w2+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #146: @9 = -0.173648 */
  w9 = -1.7364817766693030e-01;
  /* #147: @8 = input[1][1] */
  w8 = arg[1] ? arg[1][3] : 0;
  /* #148: @8 = (@9*@8) */
  w8  = (w9*w8);
  /* #149: @5 = (@5-@8) */
  w5 -= w8;
  /* #150: output[0][6] = @5 */
  if (res[0]) res[0][6] = w5;
  /* #151: @17 = zeros(16x7,28nz) */
  casadi_clear(w17, 28);
  /* #152: @18 = ones(16x1,5nz) */
  casadi_fill(w18, 5, 1.);
  /* #153: {@5, NULL, @8, NULL, NULL} = vertsplit(@18) */
  w5 = w18[0];
  w8 = w18[1];
  /* #154: @11 = mac(@4,@8,@6) */
  casadi_copy((&w6), 1, (&w11));
  casadi_mtimes(w4, casadi_s2, (&w8), casadi_s1, (&w11), casadi_s0, w, 0);
  /* #155: @19 = mac(@13,@8,@6) */
  casadi_copy((&w6), 1, (&w19));
  casadi_mtimes(w13, casadi_s2, (&w8), casadi_s1, (&w19), casadi_s0, w, 0);
  /* #156: @20 = mac(@14,@8,@6) */
  casadi_copy((&w6), 1, (&w20));
  casadi_mtimes(w14, casadi_s2, (&w8), casadi_s1, (&w20), casadi_s0, w, 0);
  /* #157: @21 = mac(@15,@8,@6) */
  casadi_copy((&w6), 1, (&w21));
  casadi_mtimes(w15, casadi_s2, (&w8), casadi_s1, (&w21), casadi_s0, w, 0);
  /* #158: @22 = mac(@16,@8,@6) */
  casadi_copy((&w6), 1, (&w22));
  casadi_mtimes(w16, casadi_s2, (&w8), casadi_s1, (&w22), casadi_s0, w, 0);
  /* #159: @23 = mac(@0,@8,@6) */
  casadi_copy((&w6), 1, (&w23));
  casadi_mtimes(w0, casadi_s2, (&w8), casadi_s1, (&w23), casadi_s0, w, 0);
  /* #160: @8 = mac(@3,@5,@6) */
  casadi_copy((&w6), 1, (&w8));
  casadi_mtimes(w3, casadi_s2, (&w5), casadi_s1, (&w8), casadi_s0, w, 0);
  /* #161: @24 = vertcat(@11, @19, @20, @21, @22, @23, @8) */
  rr=w24;
  *rr++ = w11;
  *rr++ = w19;
  *rr++ = w20;
  *rr++ = w21;
  *rr++ = w22;
  *rr++ = w23;
  *rr++ = w8;
  /* #162: (@17[:28:4] = @24) */
  for (rr=w17+0, ss=w24; rr!=w17+28; rr+=4) *rr = *ss++;
  /* #163: @25 = ones(16x1,2nz) */
  casadi_fill(w25, 2, 1.);
  /* #164: {@11, NULL, @19, NULL, NULL} = vertsplit(@25) */
  w11 = w25[0];
  w19 = w25[1];
  /* #165: @20 = mac(@4,@19,@6) */
  casadi_copy((&w6), 1, (&w20));
  casadi_mtimes(w4, casadi_s2, (&w19), casadi_s3, (&w20), casadi_s0, w, 0);
  /* #166: @21 = mac(@13,@19,@6) */
  casadi_copy((&w6), 1, (&w21));
  casadi_mtimes(w13, casadi_s2, (&w19), casadi_s3, (&w21), casadi_s0, w, 0);
  /* #167: @22 = mac(@14,@19,@6) */
  casadi_copy((&w6), 1, (&w22));
  casadi_mtimes(w14, casadi_s2, (&w19), casadi_s3, (&w22), casadi_s0, w, 0);
  /* #168: @23 = mac(@15,@19,@6) */
  casadi_copy((&w6), 1, (&w23));
  casadi_mtimes(w15, casadi_s2, (&w19), casadi_s3, (&w23), casadi_s0, w, 0);
  /* #169: @8 = mac(@16,@19,@6) */
  casadi_copy((&w6), 1, (&w8));
  casadi_mtimes(w16, casadi_s2, (&w19), casadi_s3, (&w8), casadi_s0, w, 0);
  /* #170: @5 = mac(@0,@19,@6) */
  casadi_copy((&w6), 1, (&w5));
  casadi_mtimes(w0, casadi_s2, (&w19), casadi_s3, (&w5), casadi_s0, w, 0);
  /* #171: @19 = mac(@3,@11,@6) */
  casadi_copy((&w6), 1, (&w19));
  casadi_mtimes(w3, casadi_s2, (&w11), casadi_s3, (&w19), casadi_s0, w, 0);
  /* #172: @24 = vertcat(@20, @21, @22, @23, @8, @5, @19) */
  rr=w24;
  *rr++ = w20;
  *rr++ = w21;
  *rr++ = w22;
  *rr++ = w23;
  *rr++ = w8;
  *rr++ = w5;
  *rr++ = w19;
  /* #173: (@17[1:29:4] = @24) */
  for (rr=w17+1, ss=w24; rr!=w17+29; rr+=4) *rr = *ss++;
  /* #174: @25 = ones(16x1,2nz) */
  casadi_fill(w25, 2, 1.);
  /* #175: {@20, NULL, @21, NULL, NULL} = vertsplit(@25) */
  w20 = w25[0];
  w21 = w25[1];
  /* #176: @22 = mac(@4,@21,@6) */
  casadi_copy((&w6), 1, (&w22));
  casadi_mtimes(w4, casadi_s2, (&w21), casadi_s4, (&w22), casadi_s0, w, 0);
  /* #177: @23 = mac(@13,@21,@6) */
  casadi_copy((&w6), 1, (&w23));
  casadi_mtimes(w13, casadi_s2, (&w21), casadi_s4, (&w23), casadi_s0, w, 0);
  /* #178: @8 = mac(@14,@21,@6) */
  casadi_copy((&w6), 1, (&w8));
  casadi_mtimes(w14, casadi_s2, (&w21), casadi_s4, (&w8), casadi_s0, w, 0);
  /* #179: @5 = mac(@15,@21,@6) */
  casadi_copy((&w6), 1, (&w5));
  casadi_mtimes(w15, casadi_s2, (&w21), casadi_s4, (&w5), casadi_s0, w, 0);
  /* #180: @19 = mac(@16,@21,@6) */
  casadi_copy((&w6), 1, (&w19));
  casadi_mtimes(w16, casadi_s2, (&w21), casadi_s4, (&w19), casadi_s0, w, 0);
  /* #181: @11 = mac(@0,@21,@6) */
  casadi_copy((&w6), 1, (&w11));
  casadi_mtimes(w0, casadi_s2, (&w21), casadi_s4, (&w11), casadi_s0, w, 0);
  /* #182: @6 = mac(@3,@20,@6) */
  casadi_mtimes(w3, casadi_s2, (&w20), casadi_s4, (&w6), casadi_s0, w, 0);
  /* #183: @24 = vertcat(@22, @23, @8, @5, @19, @11, @6) */
  rr=w24;
  *rr++ = w22;
  *rr++ = w23;
  *rr++ = w8;
  *rr++ = w5;
  *rr++ = w19;
  *rr++ = w11;
  *rr++ = w6;
  /* #184: (@17[2:30:4] = @24) */
  for (rr=w17+2, ss=w24; rr!=w17+30; rr+=4) *rr = *ss++;
  /* #185: @24 = ones(16x1,7nz) */
  casadi_fill(w24, 7, 1.);
  /* #186: {NULL, @22, NULL, NULL, @10} = vertsplit(@24) */
  w22 = w24[0];
  casadi_copy(w24+1, 6, w10);
  /* #187: @23 = @10[0] */
  for (rr=(&w23), ss=w10+0; ss!=w10+1; ss+=1) *rr++ = *ss;
  /* #188: @8 = @10[1] */
  for (rr=(&w8), ss=w10+1; ss!=w10+2; ss+=1) *rr++ = *ss;
  /* #189: @5 = @10[2] */
  for (rr=(&w5), ss=w10+2; ss!=w10+3; ss+=1) *rr++ = *ss;
  /* #190: @19 = @10[3] */
  for (rr=(&w19), ss=w10+3; ss!=w10+4; ss+=1) *rr++ = *ss;
  /* #191: @11 = @10[4] */
  for (rr=(&w11), ss=w10+4; ss!=w10+5; ss+=1) *rr++ = *ss;
  /* #192: @6 = @10[5] */
  for (rr=(&w6), ss=w10+5; ss!=w10+6; ss+=1) *rr++ = *ss;
  /* #193: @9 = (@9*@22) */
  w9 *= w22;
  /* #194: @9 = (-@9) */
  w9 = (- w9 );
  /* #195: @24 = vertcat(@23, @8, @5, @19, @11, @6, @9) */
  rr=w24;
  *rr++ = w23;
  *rr++ = w8;
  *rr++ = w5;
  *rr++ = w19;
  *rr++ = w11;
  *rr++ = w6;
  *rr++ = w9;
  /* #196: (@17[3:31:4] = @24) */
  for (rr=w17+3, ss=w24; rr!=w17+31; rr+=4) *rr = *ss++;
  /* #197: output[1][0] = @17 */
  casadi_copy(w17, 28, res[1]);
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_constr_h_fun_jac_uxt_zt(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int quadrotor_constr_h_fun_jac_uxt_zt_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_constr_h_fun_jac_uxt_zt_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadrotor_constr_h_fun_jac_uxt_zt_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int quadrotor_constr_h_fun_jac_uxt_zt_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadrotor_constr_h_fun_jac_uxt_zt_release(int mem) {
}

CASADI_SYMBOL_EXPORT void quadrotor_constr_h_fun_jac_uxt_zt_incref(void) {
}

CASADI_SYMBOL_EXPORT void quadrotor_constr_h_fun_jac_uxt_zt_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int quadrotor_constr_h_fun_jac_uxt_zt_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int quadrotor_constr_h_fun_jac_uxt_zt_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real quadrotor_constr_h_fun_jac_uxt_zt_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadrotor_constr_h_fun_jac_uxt_zt_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadrotor_constr_h_fun_jac_uxt_zt_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadrotor_constr_h_fun_jac_uxt_zt_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s5;
    case 1: return casadi_s6;
    case 2: return casadi_s7;
    case 3: return casadi_s8;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadrotor_constr_h_fun_jac_uxt_zt_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s9;
    case 1: return casadi_s10;
    case 2: return casadi_s11;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int quadrotor_constr_h_fun_jac_uxt_zt_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 11;
  if (sz_res) *sz_res = 8;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 106;
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_constr_h_fun_jac_uxt_zt_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 11*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 8*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 106*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
