/* This file was automatically generated by CasADi 3.6.7.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) quadrotor_expl_vde_forw_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_project CASADI_PREFIX(project)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_s9 CASADI_PREFIX(s9)
#define casadi_trans CASADI_PREFIX(trans)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

void casadi_trans(const casadi_real* x, const casadi_int* sp_x, casadi_real* y,
    const casadi_int* sp_y, casadi_int* tmp) {
  casadi_int ncol_x, nnz_x, ncol_y, k;
  const casadi_int* row_x, *colind_y;
  ncol_x = sp_x[1];
  nnz_x = sp_x[2 + ncol_x];
  row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2;
  for (k=0; k<ncol_y; ++k) tmp[k] = colind_y[k];
  for (k=0; k<nnz_x; ++k) {
    y[tmp[row_x[k]]++] = x[k];
  }
}

void casadi_project(const casadi_real* x, const casadi_int* sp_x, casadi_real* y, const casadi_int* sp_y, casadi_real* w) {
  casadi_int ncol_x, ncol_y, i, el;
  const casadi_int *colind_x, *row_x, *colind_y, *row_y;
  ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y + 2 + ncol_y+1;
  for (i=0; i<ncol_x; ++i) {
    for (el=colind_y[i]; el<colind_y[i+1]; ++el) w[row_y[el]] = 0;
    for (el=colind_x[i]; el<colind_x[i+1]; ++el) w[row_x[el]] = x[el];
    for (el=colind_y[i]; el<colind_y[i+1]; ++el) y[el] = w[row_y[el]];
  }
}

static const casadi_int casadi_s0[10] = {12, 4, 0, 1, 2, 3, 3, 3, 4, 5};
static const casadi_int casadi_s1[18] = {4, 12, 0, 0, 0, 0, 1, 2, 3, 3, 3, 3, 3, 3, 3, 0, 1, 2};
static const casadi_int casadi_s2[22] = {12, 4, 0, 4, 8, 12, 15, 0, 1, 2, 3, 0, 1, 2, 4, 0, 1, 2, 5, 0, 1, 2};
static const casadi_int casadi_s3[19] = {12, 4, 0, 3, 6, 9, 12, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2};
static const casadi_int casadi_s4[16] = {12, 1, 0, 12, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11};
static const casadi_int casadi_s5[159] = {12, 12, 0, 12, 24, 36, 48, 60, 72, 84, 96, 108, 120, 132, 144, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11};
static const casadi_int casadi_s6[55] = {12, 4, 0, 12, 24, 36, 48, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11};
static const casadi_int casadi_s7[8] = {4, 1, 0, 4, 0, 1, 2, 3};
static const casadi_int casadi_s8[7] = {3, 1, 0, 3, 0, 1, 2};
static const casadi_int casadi_s9[51] = {12, 12, 0, 3, 6, 9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2};

static const casadi_real casadi_c0[3] = {0., 0., 1.};

/* quadrotor_expl_vde_forw:(i0[12],i1[12x12],i2[12x4],i3[4],i4[3])->(o0[12],o1[12x12,36nz],o2[12x4,15nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i;
  casadi_real *rr, *ss;
  const casadi_real *cs;
  casadi_real *w0=w+12, w1, *w2=w+16, *w3=w+19, *w4=w+25, *w5=w+169, *w6=w+181, *w7=w+193, *w8=w+205, *w9=w+217, *w10=w+229, *w11=w+241, *w12=w+253, *w13=w+265, *w14=w+277, *w15=w+289, *w16=w+301, *w17=w+313, *w18=w+317, *w19=w+332, *w22=w+380, *w23=w+383, *w24=w+386, *w25=w+389;
  /* #0: @0 = input[0][1] */
  casadi_copy(arg[0] ? arg[0]+3 : 0, 3, w0);
  /* #1: output[0][0] = @0 */
  casadi_copy(w0, 3, res[0]);
  /* #2: @0 = input[3][0] */
  casadi_copy(arg[3], 3, w0);
  /* #3: @1 = 9.81 */
  w1 = 9.8100000000000005e+00;
  /* #4: @2 = [0, 0, 1] */
  casadi_copy(casadi_c0, 3, w2);
  /* #5: @2 = (@1*@2) */
  for (i=0, rr=w2, cs=w2; i<3; ++i) (*rr++)  = (w1*(*cs++));
  /* #6: @0 = (@0-@2) */
  for (i=0, rr=w0, cs=w2; i<3; ++i) (*rr++) -= (*cs++);
  /* #7: output[0][1] = @0 */
  if (res[0]) casadi_copy(w0, 3, res[0]+3);
  /* #8: @3 = zeros(6x1) */
  casadi_clear(w3, 6);
  /* #9: output[0][2] = @3 */
  if (res[0]) casadi_copy(w3, 6, res[0]+6);
  /* #10: @4 = input[1][0] */
  casadi_copy(arg[1], 144, w4);
  /* #11: {@5, @6, @7, @8, @9, @10, @11, @12, @13, @14, @15, @16} = horzsplit(@4) */
  casadi_copy(w4, 12, w5);
  casadi_copy(w4+12, 12, w6);
  casadi_copy(w4+24, 12, w7);
  casadi_copy(w4+36, 12, w8);
  casadi_copy(w4+48, 12, w9);
  casadi_copy(w4+60, 12, w10);
  casadi_copy(w4+72, 12, w11);
  casadi_copy(w4+84, 12, w12);
  casadi_copy(w4+96, 12, w13);
  casadi_copy(w4+108, 12, w14);
  casadi_copy(w4+120, 12, w15);
  casadi_copy(w4+132, 12, w16);
  /* #12: {NULL, @0, NULL} = vertsplit(@5) */
  casadi_copy(w5+3, 3, w0);
  /* #13: output[1][0] = @0 */
  casadi_copy(w0, 3, res[1]);
  /* #14: {NULL, @0, NULL} = vertsplit(@6) */
  casadi_copy(w6+3, 3, w0);
  /* #15: output[1][1] = @0 */
  if (res[1]) casadi_copy(w0, 3, res[1]+3);
  /* #16: {NULL, @0, NULL} = vertsplit(@7) */
  casadi_copy(w7+3, 3, w0);
  /* #17: output[1][2] = @0 */
  if (res[1]) casadi_copy(w0, 3, res[1]+6);
  /* #18: {NULL, @0, NULL} = vertsplit(@8) */
  casadi_copy(w8+3, 3, w0);
  /* #19: output[1][3] = @0 */
  if (res[1]) casadi_copy(w0, 3, res[1]+9);
  /* #20: {NULL, @0, NULL} = vertsplit(@9) */
  casadi_copy(w9+3, 3, w0);
  /* #21: output[1][4] = @0 */
  if (res[1]) casadi_copy(w0, 3, res[1]+12);
  /* #22: {NULL, @0, NULL} = vertsplit(@10) */
  casadi_copy(w10+3, 3, w0);
  /* #23: output[1][5] = @0 */
  if (res[1]) casadi_copy(w0, 3, res[1]+15);
  /* #24: {NULL, @0, NULL} = vertsplit(@11) */
  casadi_copy(w11+3, 3, w0);
  /* #25: output[1][6] = @0 */
  if (res[1]) casadi_copy(w0, 3, res[1]+18);
  /* #26: {NULL, @0, NULL} = vertsplit(@12) */
  casadi_copy(w12+3, 3, w0);
  /* #27: output[1][7] = @0 */
  if (res[1]) casadi_copy(w0, 3, res[1]+21);
  /* #28: {NULL, @0, NULL} = vertsplit(@13) */
  casadi_copy(w13+3, 3, w0);
  /* #29: output[1][8] = @0 */
  if (res[1]) casadi_copy(w0, 3, res[1]+24);
  /* #30: {NULL, @0, NULL} = vertsplit(@14) */
  casadi_copy(w14+3, 3, w0);
  /* #31: output[1][9] = @0 */
  if (res[1]) casadi_copy(w0, 3, res[1]+27);
  /* #32: {NULL, @0, NULL} = vertsplit(@15) */
  casadi_copy(w15+3, 3, w0);
  /* #33: output[1][10] = @0 */
  if (res[1]) casadi_copy(w0, 3, res[1]+30);
  /* #34: {NULL, @0, NULL} = vertsplit(@16) */
  casadi_copy(w16+3, 3, w0);
  /* #35: output[1][11] = @0 */
  if (res[1]) casadi_copy(w0, 3, res[1]+33);
  /* #36: @0 = zeros(4x12,3nz) */
  casadi_clear(w0, 3);
  /* #37: @17 = ones(4x1) */
  casadi_fill(w17, 4, 1.);
  /* #38: {@2, NULL} = vertsplit(@17) */
  casadi_copy(w17, 3, w2);
  /* #39: (@0[:3] = @2) */
  for (rr=w0+0, ss=w2; rr!=w0+3; rr+=1) *rr = *ss++;
  /* #40: @2 = @0' */
  casadi_trans(w0,casadi_s1, w2, casadi_s0, iw);
  /* #41: @18 = project(@2) */
  casadi_project(w2, casadi_s0, w18, casadi_s2, w);
  /* #42: @19 = input[2][0] */
  casadi_copy(arg[2], 48, w19);
  /* #43: {@16, @15, @14, @13} = horzsplit(@19) */
  casadi_copy(w19, 12, w16);
  casadi_copy(w19+12, 12, w15);
  casadi_copy(w19+24, 12, w14);
  casadi_copy(w19+36, 12, w13);
  /* #44: {NULL, @2, NULL} = vertsplit(@16) */
  casadi_copy(w16+3, 3, w2);
  /* #45: @20 = zeros(3x1,0nz) */
  /* #46: @21 = zeros(6x1,0nz) */
  /* #47: @0 = vertcat(@2, @20, @21) */
  rr=w0;
  for (i=0, cs=w2; i<3; ++i) *rr++ = *cs++;
  /* #48: {NULL, @2, NULL} = vertsplit(@15) */
  casadi_copy(w15+3, 3, w2);
  /* #49: @22 = vertcat(@2, @20, @21) */
  rr=w22;
  for (i=0, cs=w2; i<3; ++i) *rr++ = *cs++;
  /* #50: {NULL, @2, NULL} = vertsplit(@14) */
  casadi_copy(w14+3, 3, w2);
  /* #51: @23 = vertcat(@2, @20, @21) */
  rr=w23;
  for (i=0, cs=w2; i<3; ++i) *rr++ = *cs++;
  /* #52: {NULL, @2, NULL} = vertsplit(@13) */
  casadi_copy(w13+3, 3, w2);
  /* #53: @24 = vertcat(@2, @20, @21) */
  rr=w24;
  for (i=0, cs=w2; i<3; ++i) *rr++ = *cs++;
  /* #54: @13 = horzcat(@0, @22, @23, @24) */
  rr=w13;
  for (i=0, cs=w0; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w22; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w23; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w24; i<3; ++i) *rr++ = *cs++;
  /* #55: @25 = project(@13) */
  casadi_project(w13, casadi_s3, w25, casadi_s2, w);
  /* #56: @18 = (@18+@25) */
  for (i=0, rr=w18, cs=w25; i<15; ++i) (*rr++) += (*cs++);
  /* #57: output[2][0] = @18 */
  casadi_copy(w18, 15, res[2]);
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_expl_vde_forw(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int quadrotor_expl_vde_forw_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_expl_vde_forw_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadrotor_expl_vde_forw_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int quadrotor_expl_vde_forw_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadrotor_expl_vde_forw_release(int mem) {
}

CASADI_SYMBOL_EXPORT void quadrotor_expl_vde_forw_incref(void) {
}

CASADI_SYMBOL_EXPORT void quadrotor_expl_vde_forw_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int quadrotor_expl_vde_forw_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int quadrotor_expl_vde_forw_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real quadrotor_expl_vde_forw_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadrotor_expl_vde_forw_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadrotor_expl_vde_forw_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadrotor_expl_vde_forw_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    case 1: return casadi_s5;
    case 2: return casadi_s6;
    case 3: return casadi_s7;
    case 4: return casadi_s8;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadrotor_expl_vde_forw_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    case 1: return casadi_s9;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int quadrotor_expl_vde_forw_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 9;
  if (sz_res) *sz_res = 15;
  if (sz_iw) *sz_iw = 5;
  if (sz_w) *sz_w = 404;
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_expl_vde_forw_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 9*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 15*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 5*sizeof(casadi_int);
  if (sz_w) *sz_w = 404*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
